
export const MAJORS: string[] = [
        'Accounting',
        'Advertising',
        'Aerospace Engineering',
        'Agricultural education and Communication',
        'Agricultural Operations Management',
        'Anthropology',
        'Applied Physiology and Kinesiology',
        'Architecture',
        'Art History',
        'Art',
        'Astronomy and Astrophysics',
        'Biological Engineering',
        'Biology',
        'Biomedical Engineering',
        'Business Administration',
        'Chemical Engineering',
        'Chemistry',
        'Civil Engineering',
        'Communication Sciences and Disorders',
        'Computer Engineering',
        'Computer Science',
        'Construction Management',
        'Dance',
        'Data Science',
        'Dietetics',
        'Digital Arts and Sciences (Engineering)',
        'Economics',
        'Education Sciences',
        'Education',
        'Electrical Engineering',
        'English',
        'Entomology and Nematology',
        'Environmental Engineering',
        'Environmental Sciences',
        'Family, Youth and Community Sciences',
        'Finance',
        'Food and Resource Economics',
        'Food Science',
        'Forest Resources and Conservation',
        'Geography',
        'Geology',
        'Graphic Design',
        'Health Education and Behavior',
        'Health Science',
        'History',
        'Industrial and Systems Engineering',
        'Information Systems',
        'Interior Design',
        'Health Education and Behavior',
        'Health Science',
        'History',
        'Industrial and Systems Engineering',
        'Information Systems',
        'Interior Design',
        'International Studies',
        'Journalism',
        'Linguistics',
        'Management',
        'Marine Sciences',
        'Marketing',
        'Materials Science and Engineering',
        'Mathematics',
        'Mechanical Engineering',
        'Microbiology and Cell Science',
        'Music',
        'Natural Resource Conservation',
        'Nuclear and Radiological Sciences',
        'Nuclear Engineering',
        'Nursing',
        'Nutritional Sciences',
        'Pharmacy',
        'Physics',
        'Plant Science',
        'Political Science',
        'Psychology',
        'Public Health',
        'Public Relations',
        'Sociology',
        'Soil and Water Sciences',
        'Sport Management',
        'Statistics',
        'Sustainability Studies',
        'Telecommunication',
        'Theatre',
        'Tourism, Hospitality and Event Management',
        'Wildlife Ecology and Conservation',
        'Womens Studies',
        'Zoology'
]